import { query } from '../config/db.js';

export async function getAnswerAnalyticsRows(interviewId) {
  const result = await query(
    `SELECT a.id, q.order_index, q.text AS question_text, q.category,
            a.duration_seconds, a.speaking_metrics
     FROM answers a
     JOIN questions q ON q.id = a.question_id
     WHERE a.interview_id = $1
     ORDER BY q.order_index ASC`,
    [interviewId]
  );
  return result.rows;
}

/**
 * Aggregates speaking analytics purely from stored data. Every figure here
 * is a straightforward count or average over real rows — nothing is
 * estimated or generated by AI.
 */
export function aggregateSpeakingAnalytics(rows) {
  const questionsAnswered = rows.length;

  const durations = rows.map((r) => r.duration_seconds).filter((d) => Number.isFinite(d));
  const averageAnswerDurationSeconds =
    durations.length > 0 ? Math.round(durations.reduce((sum, d) => sum + d, 0) / durations.length) : null;

  const withSpeech = rows.filter((r) => r.speaking_metrics);
  const answersWithSpeechCount = withSpeech.length;

  let averageSpeakingSpeedWpm = null;
  let totalFillerWords = 0;
  let totalLongPauses = 0;
  const fillerWordBreakdown = {};

  if (withSpeech.length > 0) {
    const speeds = withSpeech.map((r) => r.speaking_metrics.speakingSpeedWpm).filter(Number.isFinite);
    if (speeds.length > 0) {
      averageSpeakingSpeedWpm = Math.round(speeds.reduce((sum, s) => sum + s, 0) / speeds.length);
    }

    withSpeech.forEach((r) => {
      const m = r.speaking_metrics;
      totalFillerWords += m.fillerWordCount || 0;
      totalLongPauses += m.longPauseCount || 0;
      Object.entries(m.fillerWordBreakdown || {}).forEach(([word, count]) => {
        fillerWordBreakdown[word] = (fillerWordBreakdown[word] || 0) + count;
      });
    });
  }

  const perAnswer = rows.map((r) => ({
    orderIndex: r.order_index,
    category: r.category,
    durationSeconds: r.duration_seconds,
    hasSpeechData: Boolean(r.speaking_metrics),
    speakingSpeedWpm: r.speaking_metrics?.speakingSpeedWpm ?? null,
    fillerWordCount: r.speaking_metrics?.fillerWordCount ?? null,
    longPauseCount: r.speaking_metrics?.longPauseCount ?? null,
  }));

  return {
    questionsAnswered,
    averageAnswerDurationSeconds,
    answersWithSpeechCount,
    averageSpeakingSpeedWpm,
    totalFillerWords,
    totalLongPauses,
    fillerWordBreakdown,
    perAnswer,
  };
}